# Generated by Django 3.1 on 2021-05-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('index', models.IntegerField(blank=True, default=-1)),
                ('Product_omschrijving', models.CharField(max_length=100)),
                ('Productgroep_oms', models.CharField(choices=[('Aardappelen en knolgewassen', 'Aardappelen en knolgewassen'), ('Alcoholische dranken', 'Alcoholische dranken'), ('Brood', 'Brood'), ('Diversen', 'Diversen'), ('Eieren', 'Eieren'), ('Flesvoeding en preparaten', 'Flesvoeding en preparaten'), ('Fruit', 'Fruit'), ('Gebak en koek', 'Gebak en koek'), ('Graanproducten en bindmiddelen', 'Graanproducten en bindmiddelen'), ('Groente', 'Groente'), ('Hartig broodbeleg', 'Hartig broodbeleg'), ('Hartige sauzen', 'Hartige sauzen'), ('Hartige snacks en zoutjes', 'Hartige snacks en zoutjes'), ('Kaas', 'Kaas'), ('Kruiden en specerijen', 'Kruiden en specerijen'), ('Melk en melkproducten', 'Melk en melkproducten'), ('Niet-alcoholische dranken', 'Niet-alcoholische dranken'), ('Noten en zaden', 'Noten en zaden'), ('Peulvruchten', 'Peulvruchten'), ('Samengestelde gerechten', 'Samengestelde gerechten'), ('Soepen', 'Soepen'), ('Suiker, snoep, zoet beleg en zoete sauzen', 'Suiker, snoep, zoet beleg en zoete sauzen'), ('Vetten en oliën', 'Vetten en oliën'), ('Vis', 'Vis'), ('Vlees en gevogelte', 'Vlees en gevogelte'), ('Vleesvervangers en zuivelvervangers', 'Vleesvervangers en zuivelvervangers'), ('Vleeswaren', 'Vleeswaren')], default='Diversen', max_length=100)),
                ('ENERCC_kcal', models.IntegerField()),
                ('PROT_g', models.FloatField()),
                ('CHO_g', models.FloatField()),
                ('FAT_g', models.FloatField()),
            ],
        ),
    ]
