# Generated by Django 3.0.10 on 2021-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='index',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
